#!/usr/bin/env bash
# Phase 2c Task 24 / NC11 clause (c): write the row-set fixtures into a
# qf-research checkout.
#
# Tooling, not a test -- the same shape as nc-fixtures-phase2b.sh. It writes
# files and prints the git commands; it never commits and never pushes, because
# the branch is the operator's to publish with the AGENT's credential. The
# dispatcher's token is read-only and must stay so.
#
#   ./nc-fixtures-phase2c.sh ~/qf-research
#
# WHY A FIXTURE AND NOT A MUTATION. NC11 used to edit a finished probe's
# `predictions.parquet` and watch the evaluation refuse. That worked because the
# relay staged the candidate's own `out/` directory, which carries no recorded
# digest -- so the control passed BECAUSE OF the defect it should have found.
# With the relay now bound to the digest `add_artifact` recorded at finish, a
# post-hoc mutation is refused before the row set is ever read, and the ONLY
# thing that can exercise the row-set property is a candidate that legitimately
# emits an unscorable set.
#
# FIVE SCRIPTS, AND THE FIRST ONE IS THE POINT. `nc11_honest` must be ACCEPTED.
# Without it, an evaluator that refused everything would satisfy every other
# clause in the group, and this suite has voided for exactly that reason before.
set -Eeuo pipefail
trap 'echo "FATAL: ${BASH_SOURCE[0]}:${LINENO} failed (exit $?)" >&2; exit 1' ERR

REPO="${1:-}"
if [ -z "$REPO" ] || [ ! -d "$REPO/.git" ]; then
  echo "usage: $0 <path to a qf-research checkout>" >&2
  exit 2
fi
if [ ! -f "$REPO/trainer/pyproject.toml" ]; then
  echo "$REPO does not look like qf-research: no trainer/pyproject.toml" >&2
  exit 2
fi

EXP="$REPO/research/experiments"
mkdir -p "$EXP"

# THE FIXTURE BRANCH MUST CARRY EVERY FIXTURE, because the suite resolves them
# all from ONE sha (`nc12-sha.txt`). This refuses rather than writing into a
# checkout that has only half of them: NC19's first live run voided with
# `can't open file '/app/trainer/research/experiments/baseline_contract.py'`
# because the 2c fixtures had been committed to a fresh branch off main, which
# does not carry 2b's. A generator that lets that happen is a generator that
# produces a branch the suite cannot use.
missing=""
for needed in extract_contract.py baseline_contract.py; do
  [ -f "$EXP/$needed" ] || missing="$missing $needed"
done
if [ -n "$missing" ]; then
  echo "$REPO/research/experiments is missing:$missing" >&2
  echo >&2
  echo "The NC suite resolves EVERY fixture from one commit -- the sha in" >&2
  echo "host/nc12-sha.txt -- so a branch with only these five scripts makes" >&2
  echo "NC13 and NC19 void. Write 2b's first, then re-run this:" >&2
  echo "    ./nc-fixtures-phase2b.sh $REPO" >&2
  echo "    ./nc-fixtures-phase2c.sh $REPO" >&2
  echo "and commit all seven files in one commit." >&2
  exit 2
fi

# The shared core, written once here and into each file: the fixtures are
# standalone because a probe names ONE path and a sibling import inside the
# sandbox is a second thing to be wrong. The duplication lives in this generator,
# where it is maintained once.
CORE="$(cat <<'CORE_PY'
"""NC11 fixture: MODE_NAME. GENERATED by host/nc-fixtures-phase2c.sh.

WHY THESE FIXTURES EXIST AT ALL. NC11's row-set property used to be exercised by
mutating a finished probe's `predictions.parquet` and watching the evaluation
refuse. That control passed BECAUSE OF a defect: the relay staged the candidate's
own `out/` directory, which has no recorded digest, so bytes could change after a
run succeeded and still be judged as that run. The relay now stages
`artifacts/predictions.parquet` and refuses on the digest `add_artifact` recorded
at finish -- which is correct, and means post-hoc mutation can no longer REACH the
row-set check. The only thing that can is a candidate which legitimately emits an
unscorable prediction set. That is what this file is.

WHAT IT IS NOT. It does not train anything. `p50` and `p90_raw` are constants,
because the property under test is the ROW SET and a fixture with a plausible
model in it invites somebody to read its verdict as a result.

EACH FIXTURE VIOLATES EXACTLY ONE PART, and would satisfy the others:

  nc11_honest        nothing -- the CANARY. Every refusal below is measured
                     against this being accepted; without it, an evaluator that
                     refused everything would satisfy the whole group.
  nc11_relabelled    part 1: row_id disagrees with its own task_id/run_id.
  nc11_ghost_row     part 2: a predicted row the extract does not contain.
  nc11_cherry_picked part 3: complete days, incomplete WITHIN them -- the rows
                     with the largest y_true dropped, which is the cherry-pick
                     that scores beautifully on a subset of a subset.
  nc11_easy_days     the day block: an earlier, easier subset of the holdout,
                     complete within each day it claims.

`nc11_cherry_picked` and `nc11_easy_days` both come back as `row_set_rejected`,
because that is the only thing the job record carries. Their distinctness is not
visible there and is not meant to be: it is in the fixtures, each of which passes
every check but one.

IT FAILS IF ITS OWN VIOLATION IS VACUOUS. A fixture that dropped zero rows, or
relabelled nothing, would emit an honest set, the evaluation would succeed, and
the suite would report a dispatcher failure for a fixture that did nothing. This
programme has shipped exactly that perturbation twice (a `sum_abs_error` of 0.0
multiplied by 1000), so the check is here rather than in the reader's head.
"""
import json
import os
import sys

# The mount points, and the ONE reason they are overridable: the repo proves what
# each fixture emits by running it against the synthetic extract in
# `evaluator/tests/test_evaluate.py` and feeding the result to the real
# evaluator. A fixture nothing can execute is a fixture whose refusal class is a
# guess. The sandbox sets neither variable.
EXTRACT = os.environ.get("NC11_EXTRACT", "/extract")
OUT = os.environ.get("NC11_OUT", "/out")

# The trainer's own holdout length (`config.compute_windows`), which is what the
# contracts are written against. Overridable for the same reason as the paths --
# the synthetic extract is three days long, not five. A MISMATCH WITH THE
# CONTRACT SHOWS UP ON THE HONEST FIXTURE as a day-block refusal, which is
# precisely why the honest one is the canary.
HOLDOUT_DAYS = int(os.environ.get("NC11_HOLDOUT_DAYS", "5"))

# The contract's primary slice. Same story: the candidate does not get to see the
# contract (that is NC9), so this is the convention, and disagreeing with it
# shows up as the honest fixture losing rows.
PRIMARY_SLICE = ("completed",)

MODE = "MODE_NAME"

TARGET_COLUMNS = {"wait_time": "wait_duration_s",
                  "run_duration": "run_duration_s"}

P50 = 600.0
P90 = 3600.0


def required_days(as_of_date, holdout_days):
    """`[as_of_date - holdout_days, as_of_date)`, one calendar day at a time.

    A SECOND IMPLEMENTATION on purpose, like `baseline_contract.py`'s
    `canonical()`: this is agent-authored code inside the sandbox and cannot
    import the trusted module. If the two ever disagree, the disagreement is the
    finding -- and it surfaces on the honest fixture, not silently.
    """
    import datetime
    day = datetime.datetime.strptime(as_of_date, "%Y-%m-%dT%H:%M:%SZ").date()
    return [(day - datetime.timedelta(days=n)).isoformat()
            for n in range(holdout_days, 0, -1)]


def scorable():
    """The honest set: every primary-slice row on every required holdout day.

    Returns `(rows, days)` where `rows` is a list of
    `{task_id, run_id, day, y_true}` sorted by (day, task_id, run_id).
    """
    import pyarrow
    import pyarrow.compute as pc
    import pyarrow.parquet as pq

    with open(os.path.join(EXTRACT, "MANIFEST.json")) as fh:
        manifest = json.load(fh)
    request = manifest["request"]
    y_col = TARGET_COLUMNS[request["target"]]
    days = required_days(request["as_of_date"], HOLDOUT_DAYS)

    table = pq.read_table(
        os.path.join(EXTRACT, "runs.parquet"),
        columns=["task_id", "run_id", "pending_at", "reason_resolved", y_col])
    # The UTC calendar day of `pending_at`: the contract's anchor, and the same
    # derivation the evaluator uses (`pyarrow.compute.strftime`, locale C).
    day = pc.strftime(table.column("pending_at"), format="%Y-%m-%d", locale="C")
    y = table.column(y_col)
    keep = pc.and_(
        pc.is_in(day, value_set=pyarrow.array(days, pyarrow.string())),
        pc.is_in(table.column("reason_resolved"),
                 value_set=pyarrow.array(list(PRIMARY_SLICE),
                                         pyarrow.string())))
    # `is_valid` AND `is_finite`: the evaluator's judged population is
    # `isin(reason, slice) & isfinite(y_true)`, and a null is neither finite nor
    # a false -- `pc.and_` would propagate it and `filter` would drop it, which
    # happens to be right, but only by accident. `fill_null` makes it a
    # decision.
    keep = pc.and_(keep, pc.and_(pc.is_valid(y), pc.is_finite(y)))
    keep = pc.fill_null(keep, False)
    picked = table.append_column("day", day).filter(keep)

    rows = []
    for task_id, run_id, d, value in zip(
            picked.column("task_id").to_pylist(),
            picked.column("run_id").to_pylist(),
            picked.column("day").to_pylist(),
            picked.column(y_col).to_pylist()):
        rows.append({"task_id": str(task_id), "run_id": int(run_id),
                     "day": str(d), "y_true": float(value)})
    rows.sort(key=lambda r: (r["day"], r["task_id"], r["run_id"]))
    return rows, days


def emit(rows, *, row_ids=None):
    """Write `predictions.parquet` with 2b-2's frozen five columns.

    `row_ids` is a LIST rather than a callback, so the labels cannot depend on
    the order this function happens to iterate in -- one fixture supplies
    deliberately wrong ones and an order-sensitive callback would put them on
    rows it did not choose.
    """
    import pyarrow
    import pyarrow.parquet as pq

    if row_ids is None:
        row_ids = [f"{r['task_id']}:{r['run_id']}" for r in rows]
    if len(row_ids) != len(rows):
        raise AssertionError(f"{len(row_ids)} row_ids for {len(rows)} rows")
    table = pyarrow.table({
        "task_id": pyarrow.array([r["task_id"] for r in rows],
                                 pyarrow.string()),
        "run_id": pyarrow.array([r["run_id"] for r in rows], pyarrow.int32()),
        "row_id": pyarrow.array(row_ids, pyarrow.string()),
        "p50": pyarrow.array([P50] * len(rows), pyarrow.float64()),
        "p90_raw": pyarrow.array([P90] * len(rows), pyarrow.float64()),
    })
    pq.write_table(table, os.path.join(OUT, "predictions.parquet"))


def report(rows, note):
    days = sorted({r["day"] for r in rows})
    print(f"    {note}", flush=True)
    print(f"== NC11-FIXTURE: mode={MODE} rows={len(rows)}"
          f" days={len(days)} first={days[0] if days else '-'}"
          f" last={days[-1] if days else '-'} ==", flush=True)


def vacuous(why):
    """The fixture did not do the thing it exists to do. FAIL, loudly.

    Exit 1, so the PROBE fails and the NC clause voids on a fixture it can see
    the problem with -- rather than the probe succeeding with an honest set and
    the clause reporting that the evaluator failed to refuse.
    """
    print(f"FAIL  {MODE} is vacuous: {why}", flush=True)
    print(f"== NC11-FIXTURE: mode={MODE} rows=0 days=0 vacuous=1 ==", flush=True)
    return 1
CORE_PY
)"

write_fixture() {  # write_fixture <name> <tail file>
  local name="$1" tail="$2"
  {
    printf '%s\n' "${CORE//MODE_NAME/$name}"
    cat "$tail"
  } > "$EXP/$name.py"
  echo "wrote research/experiments/$name.py"
}

TAILS="$(mktemp -d)"
trap 'rm -rf "$TAILS"' EXIT
cat > "$TAILS/nc11_honest" <<'TAIL_PY'


def main():
    rows, days = scorable()
    if not rows:
        return vacuous(f"the extract has no primary-slice row on {days}, so"
                       f" there is nothing to predict. Either the extract's"
                       f" window does not cover the holdout or the slice is"
                       f" empty in it.")
    covered = sorted({r["day"] for r in rows})
    if covered != days:
        # NOT a pass and not a silent one. The honest fixture claiming the wrong
        # days is the one failure that would make every other fixture in this
        # group refuse for the wrong reason.
        return vacuous(f"the extract covers {covered} of the required {days}."
                       f" The honest fixture must claim exactly the contract's"
                       f" holdout, and NC11_HOLDOUT_DAYS={HOLDOUT_DAYS} may not"
                       f" match the contract's holdout_days.")
    emit(rows)
    report(rows, "every primary-slice row on every required day: scorable")
    return 0


if __name__ == "__main__":
    sys.exit(main())

TAIL_PY
write_fixture nc11_honest "$TAILS/nc11_honest"

cat > "$TAILS/nc11_relabelled" <<'TAIL_PY'


RELABEL_EVERY = 10


def main():
    rows, _days = scorable()
    if not rows:
        return vacuous("no rows to relabel")
    # PART 1. A FRACTION of the row_ids is shifted off its own key -- not all of
    # them, and the difference is the whole point of this fixture.
    #
    # Relabelling EVERY row was the first version, and the repo's execution of
    # these fixtures against a real extract showed what it actually produces:
    # `evaluate_refused`, "none of the predicted rows is in the frozen extract".
    # That refusal is correct and is a DIFFERENT property -- predictions made
    # against other data -- and it fires before the row set is examined at all.
    # So a fixture that broke every label would have reported the right-looking
    # failure for the wrong reason, and the NC clause asserting
    # `row_set_rejected` would have failed on a working evaluator.
    #
    # With most keys intact the join finds its rows, and what is left is exactly
    # the question part 1 asks: a row_id that disagrees with the task_id and
    # run_id beside it is either a different join key or a label nobody checked.
    labels, broken = [], 0
    for position, row in enumerate(rows):
        if position % RELABEL_EVERY == 0:
            broken += 1
            labels.append(f"{row['task_id']}:{row['run_id'] + 1}")
        else:
            labels.append(f"{row['task_id']}:{row['run_id']}")
    if broken == 0:
        return vacuous(f"one in {RELABEL_EVERY} of {len(rows)} rows rounded to"
                       f" no relabelled row")
    emit(rows, row_ids=labels)
    report(rows, f"{broken} of {len(rows)} row_ids shifted to run_id+1, the"
                 f" rest honest: the derivation is broken where the join still"
                 f" lands")
    return 0


if __name__ == "__main__":
    sys.exit(main())

TAIL_PY
write_fixture nc11_relabelled "$TAILS/nc11_relabelled"

cat > "$TAILS/nc11_ghost_row" <<'TAIL_PY'


def main():
    rows, _days = scorable()
    if not rows:
        return vacuous("no rows to add a ghost to")
    # PART 2. One extra row whose task_id is not in the extract, with a
    # PERFECTLY WELL-FORMED row_id -- so part 1 passes and the refusal can only
    # be this. A prediction for a row the extract does not contain has no y_true
    # to be scored against, and quietly dropping it would let a candidate pad its
    # coverage.
    ghost = {"task_id": "nc11-ghost-000000000000", "run_id": 0,
             "day": rows[-1]["day"], "y_true": 0.0}
    if any(r["task_id"] == ghost["task_id"] for r in rows):
        return vacuous("the ghost task_id exists in the extract")
    emit(rows + [ghost])
    report(rows + [ghost],
           f"{len(rows)} real rows plus {ghost['task_id']}, which is not in the"
           f" extract")
    return 0


if __name__ == "__main__":
    sys.exit(main())

TAIL_PY
write_fixture nc11_ghost_row "$TAILS/nc11_ghost_row"

cat > "$TAILS/nc11_cherry_picked" <<'TAIL_PY'

DROP_FRACTION = 0.25


def main():
    rows, days = scorable()
    if not rows:
        return vacuous("no rows to cherry-pick from")
    # PART 3. COMPLETE DAYS, INCOMPLETE WITHIN THEM. Every required day is still
    # claimed -- so the day block is exactly right and the refusal cannot be that
    # -- and inside each day the rows with the largest y_true are dropped. That is
    # the cherry-pick worth closing: the long tail is where a queue model is
    # worst, and a prediction set without it scores beautifully on a subset of a
    # subset while every column in it is honest.
    kept, dropped = [], 0
    for day in days:
        same = sorted((r for r in rows if r["day"] == day),
                      key=lambda r: r["y_true"])
        # At least one row stays, or the day would vanish and the day-block check
        # would refuse first -- a refusal for the right class and the wrong
        # reason, which is the kind of coverage that reads as real and is not.
        keep_n = max(1, int(round(len(same) * (1.0 - DROP_FRACTION))))
        kept.extend(same[:keep_n])
        dropped += len(same) - keep_n
    if dropped == 0:
        return vacuous(f"{DROP_FRACTION:.0%} of {len(rows)} rows across"
                       f" {len(days)} days rounded to zero dropped rows")
    if sorted({r["day"] for r in kept}) != days:
        return vacuous("dropping the tail lost a whole day, so the day-block"
                       " check would refuse before completeness is reached")
    emit(kept)
    report(kept, f"{len(kept)} of {len(rows)} rows: the {DROP_FRACTION:.0%}"
                 f" largest y_true dropped from every day, days intact")
    return 0


if __name__ == "__main__":
    sys.exit(main())

TAIL_PY
write_fixture nc11_cherry_picked "$TAILS/nc11_cherry_picked"

cat > "$TAILS/nc11_easy_days" <<'TAIL_PY'

CLAIM_DAYS = 2


def main():
    rows, days = scorable()
    if not rows:
        return vacuous("no rows to choose days from")
    if len(days) <= CLAIM_DAYS:
        return vacuous(f"the holdout is {len(days)} day(s), so claiming"
                       f" {CLAIM_DAYS} of them is not a subset")
    # THE DAY BLOCK. The two OLDEST required days, complete within each -- so
    # parts 1, 2 and 3 all pass and the only thing wrong is which days were
    # chosen. This is the vector the first version of `check_day_block` left
    # open: it enforced contiguity and merely RECORDED whether the block was the
    # expected tail, on the reasoning that the trainer might drop a partial final
    # day. It cannot -- `load_config` refuses a non-midnight `as_of_date` -- so
    # the hedge guarded nothing and left an easier earlier holdout scoreable.
    claimed = days[:CLAIM_DAYS]
    kept = [r for r in rows if r["day"] in claimed]
    if not kept:
        return vacuous(f"no row falls on {claimed}")
    if sorted({r["day"] for r in kept}) != claimed:
        return vacuous(f"the extract has rows on only"
                       f" {sorted({r['day'] for r in kept})} of {claimed}, so"
                       f" this would refuse as an extract gap rather than as a"
                       f" chosen block")
    emit(kept)
    report(kept, f"claiming {claimed} of the required {days}: an earlier block,"
                 f" complete within each day it claims")
    return 0


if __name__ == "__main__":
    sys.exit(main())

TAIL_PY
write_fixture nc11_easy_days "$TAILS/nc11_easy_days"

cat <<'NEXT'

Next, in the qf-research checkout, with the AGENT's credential:

  # ON THE EXISTING FIXTURE BRANCH, or a new branch made FROM it -- never a
  # fresh branch off main. Every fixture the suite runs comes from the single sha
  # in host/nc12-sha.txt, so a branch carrying only these five makes NC13 and
  # NC19 void on a working host.
  git checkout <the fixture branch>       # the one nc12-sha.txt points at
  git add research/experiments/nc11_honest.py \
          research/experiments/nc11_relabelled.py \
          research/experiments/nc11_ghost_row.py \
          research/experiments/nc11_cherry_picked.py \
          research/experiments/nc11_easy_days.py
  git commit -m "NC11 row-set fixtures"
  git push -u origin HEAD
  git rev-parse HEAD > <checkout>/tools/queue-forecasting/host/nc12-sha.txt
  # ^ and COMMIT that too: it is what the suite submits every fixture probe with.

Then, on the host, ONE PROBE PER SCRIPT against the same extract -- the suite
finds them by reading each SUCCEEDED probe's own spec, so the order does not
matter, but they must all judge the same data to be comparable:

  sudo -H -u research qf extracts     # copy the `--extract <hash>` line it prints
  sudo -H -u research qf baselines    # copy the `--baseline <hash>` line too
  for f in nc11_honest nc11_relabelled nc11_ghost_row nc11_cherry_picked \
           nc11_easy_days; do
    sudo -H -u research qf probe --sha <the qf-research sha> \
      --path research/experiments/$f.py --extract <request_hash> \
      --baseline <baseline_hash>
  done

--baseline IS REQUIRED HERE even though none of these scripts reads /baseline.
The evaluator refuses a run that recorded no baseline -- "the contract is stated
against baseline X, and this request carries no baseline_hash" -- and refuses
again if the pin does not EQUAL the contract's, because a relative bar measured
against another baseline is not the bar that was agreed. Without it every one of
the five comes back refused for that reason, including the honest canary, and the
group is void.

Each probe SUCCEEDS -- emitting an unscorable prediction set is not a failure,
it is the fixture's job. A probe that FAILS means its own violation was vacuous
(it says so, and prints `vacuous=1`), which is a fixture bug rather than a
finding. Then:

  sudo ./nc-suite-phase2.sh nc11

reports clause (c): the honest set accepted, the other four refused as
`row_set_rejected`.
NEXT
